{{- if not .Values.secretConfigName }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "common.names.configname" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
  {{- if .Values.commonLabels }}
  {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- end }}
data:
  elastalert_config: |-
    ---
    rules_folder: {{ .Values.rulesFolder }}
{{- if .Values.scanSubdirectories }}    
    scan_subdirectories: {{ .Values.scanSubdirectories }}
{{- end }}
    run_every:
      minutes: {{ .Values.runIntervalMins }}
{{- if .Values.realertIntervalMins }}
    realert:
      minutes: {{ .Values.realertIntervalMins }}
{{- end }}
    buffer_time:
      minutes: {{ .Values.bufferTimeMins }}
    es_host: {{ .Values.elasticsearch.host }}
    es_port: {{ .Values.elasticsearch.port }}
{{- if .Values.elasticsearch.username }}
    es_username: {{ .Values.elasticsearch.username }}
{{- end }}
{{- if .Values.elasticsearch.password }}
    es_password: {{ .Values.elasticsearch.password }}
{{- end }}
    writeback_index: {{ .Values.writebackIndex }}
    use_ssl: {{ .Values.elasticsearch.useSsl }}
    verify_certs: {{ .Values.elasticsearch.verifyCerts }}
{{- if .Values.elasticsearch.clientCert }}
    client_cert: {{ .Values.elasticsearch.clientCert }}
{{- end }}
{{- if .Values.elasticsearch.clientKey }}
    client_key: {{ .Values.elasticsearch.clientKey }}
{{- end }}
{{- if .Values.elasticsearch.caCerts }}
    ca_certs: {{ .Values.elasticsearch.caCerts }}
{{- end }}
    alert_time_limit:
      minutes: {{ .Values.alertRetryLimitMins }}
{{- if .Values.extraConfigOptions }}
{{ toYaml .Values.extraConfigOptions | indent 4 }}
{{- end }}
{{- end }}
