apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "elastalert.fullname" . }}-rules
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
  {{- if .Values.commonLabels }}
  {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- end }}
data:
{{- if .Values.rootRulesFolder }}
{{- $rulesDirectory := printf "%v/**.{yaml,yml}" .Values.rootRulesFolder -}}
{{- $enabledRules := .Values.enabledRules -}}
{{- range $rule, $_ :=  .Files.Glob $rulesDirectory -}}
  {{- $ruleBase := base $rule -}}
  {{- $ruleName := regexReplaceAll "\\.(yaml|yml)$" $ruleBase "" -}}
  {{- if has $ruleName $enabledRules }}
  {{ $ruleBase }}: |-
{{ $.Files.Get $rule | indent 4 }}
  {{- end }}
{{- end }}
{{- else }}
{{- range $key, $value := .Values.rules }}
  {{ $key }}: |-
{{ $value | indent 4 }}
{{- end }}
{{- end }}
