{{- if .Values.smtp_auth }}
apiVersion: v1
kind: Secret
metadata:
  name: elastalert-smtp-auth
  labels: {{- include "common.labels.standard" . | nindent 4 }}
  {{- if .Values.commonLabels }}
  {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- end }}
type: kubernetes.io/Opaque
stringData:
  smtp_auth.yaml: |-
    user: {{ .Values.smtp_auth.username }}
    password: {{ .Values.smtp_auth.password }}
{{- end}}
