name: publish_image

on:
  push:
    # Publish `bugfix/opsgenie-alerter-handle-keyerror-in-custom-message` as Docker image.
    branches:
      - bugfix/opsgenie-alerter-handle-keyerror-in-custom-message

env:
  IMAGE_NAME: elastalert2
  DOCKER_REPO: facilityworld/elastalert2

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Log into Docker Registry
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Install buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: latest

      - name: Build and Push multi-arch to Docker Hub
        run: |
          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

          echo VERSION=$VERSION

          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
          docker buildx build \
          --platform=linux/amd64,linux/arm64 \
          --output "type=image,push=true" \
          --file ./Dockerfile . \
          --tag $DOCKER_REPO:$VERSION

      #
      # - name: Build and push image to GitHub
      #   run: |
      #     docker build . --file Dockerfile --tag $IMAGE_NAME

      #     IMAGE_ID=docker.pkg.github.com/${{ github.repository }}/$IMAGE_NAME

      #     # Change all uppercase to lowercase
      #     IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

      #     echo IMAGE_ID=$IMAGE_ID
      #     echo VERSION=$VERSION

      #     # Push to GitHub Package
      #     docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
      #     docker push $IMAGE_ID:$VERSION
